name: CI
on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x  # Adjust version as needed

      - name: Build
        run: |
            cd src/HelloWorld 
            dotnet build 

      - name: Publish
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish
      - name: Deploy to AWS Lambda
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 
      - run: cd src/HelloWorld && dotnet restore
      - run: zip -r publish.zip ./src/HelloWorld/*
      - run: aws lambda update-function-code --function-name=HelloWorld-HelloWorldFunction-QZppcAMFCtKI  --zip-file=fileb://publish.zip 
